services:
    App\Infrastructure\Serializer\SocialNetworkDtoNormalizer:
        tags: ['serializer.normalizer']

    App\Infrastructure\Serializer\SocialNetworkDtoArrayNormalizer:
        tags: ['serializer.normalizer']

    App\Infrastructure\Serializer\SkillDtoNormalizer:
        tags: ['serializer.normalizer']
