services:
    App\Infrastructure\Serializer\SocialNetworkDtoNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 100 }

    App\Infrastructure\Serializer\SocialNetworkDtoArrayNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 90 }

    App\Infrastructure\Serializer\SkillDtoNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 80 }
