# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_NAME: ${SERVER_NAME}
